# debug
debug: True
timing: False

# system
device: cuda:0

# data
data_name: bonsai
data_dir: ./data/bonsai
image_dir: ./data/bonsai/images
downsample: 1

# renderer
tile_size: 16
near_plane: 1.5
far_plane: 1000.0
tile_culling_type: bcircle
tile_culling_thresh: 0.01
frustum_culling_radius: 10.0
tile_culling_radius: 10.0

# model
random_init: False
max_iteration: 10000
lr: 5e-3
alpha_init: 0.8
svec_init: 0.02
loss_fn: l2
T_thresh: 0.01 # early stop threshold for transmitance
ssim_loss_mult: 0.2 
ssim_loss_win_size: 11