# debug
debug: False
timing: False

# system
device: cuda:0

# data
data_name: bonsai
data_dir: ./data/bonsai
image_dir: ./data/bonsai/images
downsample: 1

# renderer
tile_size: 16
near_plane: 1.5
far_plane: 500.0
tile_culling_type: bcircle
tile_culling_thresh: 0.01
frustum_culling_radius: 5.0
tile_culling_radius: 5.0

# model
random_init: False
max_iteration: 10000
lr: 1e-2
alpha_init: 0.8
svec_init: 0.002
loss_fn: l2
T_thresh: 0.0001 # early stop threshold for transmitance
ssim_loss_mult: 0.2 
ssim_loss_win_size: 11

# activation functions
alpha_act: sigmoid
color_act: nothing

# gaussian adaptive control
pos_grad_thresh: 0.0002
scale_shrink_factor: 1.6
alpha_reset_period: 300
alpha_reset_val: 0.1
alpha_thresh: 0.05

# viewer config
viewer: False
viewer_port: 1234