# debug
debug: True
timing: True

# system
device: cuda:0

# data
data_name: fern
data_dir: ./data/llff
image_dir: ./data/llff/images_2
downsample: 2

# renderer
tile_size: 16
near_plane: 1.5
far_plane: 1000.0
tile_culling_type: bcircle
tile_culling_thresh: 0.001
frustum_culling_radius: 4.0
tile_culling_radius: 4.0

# model
max_iteration: 10000
lr: 5e-3
alpha_init: 0.8
svec_init: 0.02
loss_fn: l2
T_thresh: 0.0001 # early stop threshold for transmitance
ssim_loss_mult: 0.2 
ssim_loss_win_size: 11

# gaussian adaptive control
pos_grad_thresh: 0.0002
scale_shrink_factor: 1.6
alpha_reset_period: 3000
alpha_reset_val: 0.1
alpha_thresh: 0.01

# debug fn
fn: test_basic_alias