# debug
debug: False
timing: False

# system
mode: train_and_eval
device: cuda:0
eval_iteration: 50

# data
data_name: garden
data_dir: ./data/garden
image_dir: ./data/garden/images_2
downsample: 4
save_iteration: 1000

# renderer
tile_size: 16
near_plane: 1.5
far_plane: 1000.0
frustum_culling_radius: 1.0
tile_culling_type: aabb
tile_culling_thresh: 0.01
tile_culling_radius: 6.0

# model
svec_init_method: nearest
nearest_k: 3
random_init: False
max_iteration: 10000
lr: 1e-2
alpha_init: 0.5
svec_init: 0.02
loss_fn: l2
T_thresh: 0.01 # early stop threshold for transmitance
ssim_loss_mult: 0.2 
ssim_loss_win_size: 11

# spherical harmonics
sh_order: 3
sh_upgrades: []

# activation functions
alpha_act: sigmoid
svec_act: exp

# gaussian adaptive control
adapt_ctrl_enabled: True
warm_up: 500
adaptive_control_iteration: 101
pos_grad_thresh: 0.0002
scale_shrink_factor: 1.6
alpha_reset_period: 1000
remove_low_alpha_period: 1000
alpha_reset_val: 0.1
alpha_thresh: 0.15
split_scale_thresh: 0.02
cum_grad: False
split_type: 2d_mean_grad
split_reduction: mean
svec_thresh: 50

# wandb
wandb: False

# viewer config
viewer: False
viewer_port: 1234

# tests
only_forward: False

# lrs
mean_lr: 1e-3
qvec_lr: 1e-2
svec_lr: 1e-2
sh_coeffs_lr: 1e-2
alpha_lr: 1e-2

# misc
comment: ""

# from checkpoint
from_ckpt: True
ckpt_path: ./saved/2023-06-18_13:03:17_garden_sh/model_1000.pt
start_epoch: 500
vis_grad_thresh: 0.0002